import Validator.Regex.Compress
import Validator.Regex.Drawer
import Validator.Regex.Enter
import Validator.Regex.Extract
import Validator.Regex.Language
import Validator.Regex.Leave
import Validator.Regex.LeaveSmart
import Validator.Regex.Map
import Validator.Regex.Num
import Validator.Regex.Point
import Validator.Regex.Regex
import Validator.Regex.RegexID
import Validator.Regex.Replace
import Validator.Regex.Room
import Validator.Regex.Smart
