import Validator.Regex.Char
import Validator.Regex.Drawer
import Validator.Regex.Enter
import Validator.Regex.Extract
import Validator.Regex.IfExpr
import Validator.Regex.Lang
import Validator.Regex.Leave
import Validator.Regex.Map
import Validator.Regex.Memoize
import Validator.Regex.Num
import Validator.Regex.Point
import Validator.Regex.Regex
import Validator.Regex.RegexID
import Validator.Regex.Replace
import Validator.Regex.Room
